AWSTemplateFormatVersion: 2010-09-09
Description: |
  
Parameters:
  
  HostingZone:
    Description: Please enter a DNS name of an existing Amazon Route 53 hosted zone.
    Type: String

  HostedZoneId:
    Description: Please select the Id of the existing Amazon Route 53 hosted zone.
    Type: AWS::Route53::HostedZone::Id
  
  FullDomainName:
    Description: Please enter the full domain name for the web application.
    Type: String

Resources:
    
  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      AccessControl: PublicRead
      BucketName: !Ref FullDomainName
      WebsiteConfiguration:
        IndexDocument: index.html

  BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref FullDomainName
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub '${S3Bucket.Arn}/*'
        
  SSL:
    Type: "AWS::CertificateManager::Certificate"
    Properties:
      DomainName: !Sub ${FullDomainName}
      DomainValidationOptions:
        - DomainName: !Sub ${FullDomainName}
          HostedZoneId: !Ref HostedZoneId
      ValidationMethod: DNS

  CloudFront:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref FullDomainName
        DefaultCacheBehavior:
          AllowedMethods:
            - 'GET'
            - 'HEAD'
          CachedMethods: 
            - 'GET'
            - 'HEAD'
          CachePolicyId:  658327ea-f89d-4fab-a63d-7e88639e58f6 
          TargetOriginId: !Ref FullDomainName 
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Enabled: True
        HttpVersion: http2
        Origins: 
          - CustomOriginConfig:
              OriginProtocolPolicy: http-only
            DomainName: !GetAtt S3Bucket.DomainName
            Id: !Ref FullDomainName
        ViewerCertificate:
          AcmCertificateArn: !Ref SSL
          MinimumProtocolVersion: TLSv1
          SslSupportMethod: sni-only
          
  Route53:
    Type: "AWS::Route53::RecordSetGroup"
    Properties:
      HostedZoneId: !Ref HostedZoneId
      RecordSets:
        - AliasTarget: 
            DNSName: !GetAtt CloudFront.DomainName
            EvaluateTargetHealth: false
            HostedZoneId: Z2FDTNDATAQYW2
          Name: !Ref FullDomainName
          Type: A

Outputs:
  
  BucketName:
    Description: Name of the S3 Bucket Name
    Value: !Ref S3Bucket
  
  CloudFrontDistributionEndpoint:
    Description: Endpoint for Kittens Cloudfront Distribution
    Value: !GetAtt CloudFront.DomainName
  
  AppFullDomainName:
    Description: Full DomainName of Kittens Carousel Application
    Value: !Ref FullDomainName  