AWSTemplateFormatVersion: 2010-09-09
Description: |
  
Parameters:
  DomainName:
    Description: Please enter your a valid Route53 HostingZone.
    Type: String

  FullDomainName:
    Description: Please enter your company's full domain name.
    Type: String
    
Resources:
    
  SSL:
    Type: "AWS::CertificateManager::Certificate"
    Properties:
      DomainName: !Ref DomainName
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref Route53
      ValidationMethod: DNS

  CloudFront:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Aliases: DomainName
        CacheBehaviors:
          - AllowedMethods:
              - 'GET'
              - 'HEAD'
            CachePolicyId:  658327ea-f89d-4fab-a63d-7e88639e58f6 
            PathPattern: '*'
            TargetOriginId: e2031-Salih
            ViewerProtocolPolicy: redirect-to-https
        Enabled: True
        HttpVersion: http2
        Origins: 
          - CustomOriginConfig:
              OriginProtocolPolicy: https-only
        DomainName: www.hi-gursoy.com.s3-website-us-east-1.amazonaws.com
        Id: e2031-Salih
        ViewerCertificate:
          CloudFrontDefaultCertificate: True

  Route53HostedZone:
    Type: "AWS::Route53::HostedZone"
    Properties:
      Name: !Ref DomainName
  
  Route53RecordSet:
    Type: "AWS::Route53::RecordSet"
    Properties:
      AliasTarget:
        DNSName: !GetAtt CloudFront.DomainName
        HostedZoneId: Z2FDTNDATAQYW2
      HostedZoneId: !Ref Route53HostedZone
      Name: !Ref FullDomainName
      Region: us-east-1
      Type: A
