apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql
  template:
    metadata:
      labels:
        name: mysql
        app: phonebook
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: rootpasswd
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: username
        ports:
        - containerPort: 3306
        volumeMounts:
          - name: mysql-storage
            mountPath: /data/db
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: per-vol-claim
---

apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    name: mysql
    app: phonebook
spec:
  selector:
    name: mysql
  type: ClusterIP
  ports:
    - name: db
      port: 3306
      targetPort: 3306
