apiVersion: v1
kind: Service
metadata:
  name: search-service
  labels:
    name: search
spec:
  selector:
    name: search 
  type: NodePort
  ports:
   - name: http
     port: 3000
     nodePort: 30002
     targetPort: 80
     protocol: TCP
