version: "3.7"

services:
  
  phonebook:
    image: 130917230501.dkr.ecr.us-east-1.amazonaws.com/e2031/phonebook-app:latest
    depends_on:
      - database
    deploy:
      mode: global 
    ports:
      - "80:80"
    networks:
      - mynet

  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1111PPpp
      MYSQL_DATABASE: phonebook_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: Clarusway_1
    configs:
      - source: db-init
        target: docker-entrypoint-initdb.d/init.sql
 
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - mynet

networks:
  mynet:
    driver: overlay

volumes:
  db-data:

configs:
  db-init:
    file: ./init.sql
