version: "3.8"

services:
  
  phonebook:
    image: phonebook-app:latest
    restart: always
    depends_on:
      - database
    deploy:
      mode: global
      replicas: 1 
    ports:
      - "80:80"
    networks:
      - mynet

  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1111PPpp
      MYSQL_DATABASE: phonebook_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: Clarusway_1
    volumes:
      - db-data:/var/lib/mysql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynet

networks:
  mynet:
    driver: overlay

volumes:
  db-data: